version: '2.1'

services:
  foodgether-frontend:
    image: foodgether-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    restart: always
  foodgether-backend:
    image: foodgether-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
  chrome:
    image: browserless/chrome
    ports:
      - 5000:3000

