version: '3'

services:
  foodgether-frontend:
    image: foodgether-frontend
    container_name: foodgether-frontend
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - 8181:8181
    restart: always
    environment:
      - VITE_BASE_PATH=$VITE_BASE_PATH

  foodgether-backend:
    image: foodgether-backend
    container_name: foodgether-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - foodgether-network
    depends_on:
      - chrome
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=mongodb+srv://$FOODGETHER_MONGO_USERNAME:$FOODGETHER_MONGO_PASSWORD@lamprojects.e8cgw.mongodb.net/foodgether-prod?retryWrites=true&w=majority
      - FOODGETHER_REDIS_PORT=$FOODGETHER_REDIS_PORT
      - FOODGETHER_REDIS_HOST=$FOODGETHER_REDIS_HOST
      - FOODGETHER_REDIS_PASSWORD=$FOODGETHER_REDIS_PASSWORD
      - CHROME_URL=$CHROME_URL
      - CHROME_PORT=$CHROME_PORT
  
  chrome:
    image: browserless/chrome
    networks:
      - foodgether-network
    ports:
      - "5000:3000"

  redis:
    image: 'redis:alpine'
    container_name: foodgether-redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - FOODGETHER_REDIS_PASSWORD=$FOODGETHER_REDIS_PASSWORD
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - foodgether-network
    command: '--requirepass $FOODGETHER_REDIS_PASSWORD'
    volumes:
      - /etc/bitnami/redis:/bitnami/redis
    ports:
      - "6379:6379"

  realtime:
    image: foodgether-realtime
    container_name: foodgether-realtime
    build:
      context: ./realtime
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb+srv://$FOODGETHER_MONGO_USERNAME:$FOODGETHER_MONGO_PASSWORD@lamprojects.e8cgw.mongodb.net/foodgether-prod?retryWrites=true&w=majority
      - DATABASE_NAME=foodgether-prod
      - FOODGETHER_REDIS_PORT=$FOODGETHER_REDIS_PORT
      - FOODGETHER_REDIS_HOST=$FOODGETHER_REDIS_HOST
      - FOODGETHER_REDIS_PASSWORD=$FOODGETHER_REDIS_PASSWORD
      - PRODUCTION="PRODUCTION"
    ports:
      - 4000:4000
    depends_on:
      - envoy
      - redis

  envoy:
    container_name: foodgether-envoy
    image: envoyproxy/envoy-dev:69bb7bc6888741b2bad0ea1eec37d00f677eb85f
    ports:
      - "10000:10000"
      - "4001:4001"
      - "9901:9901"
    volumes:
      - ./envoy/envoy.prod.yaml:/etc/envoy/envoy.yaml
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      loglevel: debug


networks:
  foodgether-network:
    driver: bridge

