version: '3'

services:
  foodgether-frontend:
    image: foodgether-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    restart: always
  foodgether-backend:
    image: foodgether-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - foodgether-network
    depends_on:
      - chrome
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  chrome:
    image: browserless/chrome
    networks:
      - foodgether-network
    ports:
      - "5000:3000"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - foodgether-network
    volumes:
      - /etc/bitnami/redis:/bitnami/redis
    ports:
      - "6379:6379"


networks:
  foodgether-network:
    driver: bridge

